### PR TITLE
Update active_utils to 3.0.0, change namespace

### PR DESCRIPTION
**Pull request by ntalbott**
@karlhungus @jnormore @arthurnn @wvanbergen this is a companion PR to https://github.com/Shopify/active_utils/pull/36 and https://github.com/Shopify/active_shipping/pull/208. Please review and let me know if you need any additional tweaks.

### CODE REVIEW

**Comment by wvanbergen** [comment]
@ntalbott can we do a beta release of active_utils 3.x so we can run the tests?

**Comment by ntalbott** [comment]
@wvanbergen well, I run the tests by leveraging a [gem local override](http://bundler.io/git.html#local). I'd be fine with a beta release too, but I don't even have commit privs (nor do I really want them) on active_utils, so it's all you :smile:

**Comment by wvanbergen** [comment]
I noticed we're not running tests against Ruby 1.9. Intentional?

**Comment by wvanbergen** [comment]
OK let me see if I can do a release.

**Comment by wvanbergen** [comment]
Closing this in favor of #49

**Pull request closed without merging**
