### PR TITLE
MWS Auth Token

### PR DESCRIPTION
**Pull request by berkcaputcu**
Uses MWSAuth token when provided

@csaunders

### CODE REVIEW

**Comment by csaunders** [comment]
Tests are being wonky, but changes look good.

**Comment by berkcaputcu** [comment]
tests are failing because of this: https://github.com/Shopify/active_fulfillment/blob/4312da80c596cfbb05b77e33fabe7ae2981e37c1/test/unit/services/shopify_api_test.rb#L77 (which blames to you @csaunders :smile:  )

**Comment by csaunders** [comment]
I think that test and the `order_ids` can just be removed.

**Comment by berkcaputcu** [comment]
removed the deprecated test, can you take another quick look please?

**Pull request merged**
