### PR TITLE
Test Rails 5, active_support and active_utils

### PR DESCRIPTION
**Pull request by mikeletscher**
Adds testing for Rails 5 active_support/active_utils. Also adds upper version restriction on the ActiveSupport dependency.

@kmcphillips @jonathankwok @garethson

### CODE REVIEW

**Comment by jonathankwok** [comment]
👍  LGTM

**Comment by kmcphillips** [comment]
Mint. Looks great.

Only thing that's a little weird is that we never include the actual `Gemfile` shipped with the gem in the testing matrix.

**Comment by garethson** [comment]
🚢

**Comment by mikeletscher** [comment]
@kmcphillips I removed the original Gemfile again. According to Gemfile.lock, the ActiveSupport version for the original was 3.2.9 but the version for `Gemfile.activesupport32` is 3.2.0. The CI was failing because it was trying to use ActiveSupport 5.0.0.

**Comment by kmcphillips** [comment]
In a gem the `Gemfile.lock` is not committed. So you can't tie it to a version. But you still want to have CI testing the `Gemfile` that is distributed.

Most likely your failure was because it was trying to install 5.0 with a low version of ruby. You'll need to add that exclude to the CI matrix.

**Comment by kmcphillips** [comment]
```
- Gemfile

matrix:
  exclude:
    - rvm: 2.0
      gemfile: Gemfile
    - rvm: 2.1
      gemfile: Gemfile

**Comment by mikeletscher** [comment]
@kmcphillips Oh whoops good call.

**Pull request merged**
